language: python
python:
  - "3.6"
install:
  - python setup.py sdist
  - pip install flake8 yapf isort
before_script:
  - flake8
  - isort -rc --diff ppln_mlflow/
  - yapf -r -d ppln_mlflow/
script:
  - python setup.py test
